apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: ${module.eks.cluster_name}
  securityGroupSelector:
    karpenter.sh/discovery: ${module.eks.cluster_name}
  instanceProfile: ${module.eks_blueprints_addons.karpenter.node_instance_profile_name}
  tags:
    karpenter.sh/discovery: ${module.eks.cluster_name}
    intent: apps
    project: karpenter-patterns
    KarpenerProvisionerName: "default"
    NodeType: "default"
    IntentLabel: "apps"